services:
  - type: web
    name: ouchi-no-hatake-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ouchi-no-hatake-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production

databases:
  - name: ouchi-no-hatake-db
    databaseName: ouchi_no_hatake_production
    user: ouchi_no_hatake_user